language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r tests/requirements.txt --use-mirrors
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script:
  - python tests/manage.py test
branches:
  only:
    - master